CREATE TABLE DP_ENQ_EXECUTIVE_CUSTOMER_FEEDBACK
(
	DEALER_ID INT NOT NULL,
	BRANCH_ID INT NOT NULL,
	ENQUIRY_ID BIGINT NOT NULL,
	ENQUIRY_DATE DATETIME NOT NULL,
	EMP_ID INT NOT NULL,
	SALES_EXECUTIVE VARCHAR(100) NOT NULL,
	CUST_NAME VARCHAR(100) NOT NULL,
	PRODUCT_ENQUIRED VARCHAR(100) NOT NULL,
	UNDERSTANDING_OF_NEEDS INT NOT NULL,
	SEEKING_INFORMATION INT NOT NULL,
	EVALUATION_OF_OPTION INT NOT NULL,
	DECISION_MAKING INT NOT NULL,
	POST_PURCHASE INT NOT NULL,
	IS_BOUGHT INT NOT NULL,
	REMARKS NVARCHAR NULL,
	CREATED_ON DATETIME NOT NULL
)




