CREATE TABLE DP_MOBILE_IMAGE(
	DEALER_ID INT NULL,
	BRANCH_ID INT NULL,
	TRANS_TYPE_ID INT NULL,
	TRANS_TYPE_DESC NVARCHAR(20) NULL,
	TRANS_ID BIGINT NULL,
	IMAGE_FILE_NAME NVARCHAR(100) NULL,
	CREATED_DATE DATETIME NULL,
	INSERTED_DATE DATETIME NULL
)