------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/*
    PROCEDURE NAME     		: 	pr_getTVSSalesExecutiveEnquiryDetails
    PROGRAM UNIT TYPE 		:	Procedure
    CREATED BY              :	Vignesh
    CREATED ON             	:	19-03-2019
    PURPOSE                 :	This Procedure is to get the Enquiry converstion details based on TVS Executive    
*/
CREATE PROC pr_getTVSSalesExecutiveEnquiryDetails
(
	@EmployeeNo int
)
AS
BEGIN
IF EXISTS(SELECT 1 FROM JCP_DEALER_MASTER WHERE Empno = @EmployeeNo AND Category IN ('TM-SALES','SE-SALES'))
BEGIN


SELECT 
		 DEALER_ID
		,ENQUIRY.EMPLOYEE_NO
		,ENQUIRY.Zone
		,ENQUIRY.Sales_office
		,ENQUIRY.Territory_Key
		,ENQUIRY.DEALERSHIP_NAME
		,ENQUIRY.CITY
		,ENQUIRY.ENQUIRY_MODE
		,'AMD' AS BUSINESS_TYPE
		,ISNULL(SUM(ENQUIRY.OPEN_VAL),0) AS OPEN_VAL
		,ISNULL(SUM(ENQUIRY.CLOSED_VAL),0) AS CLOSED_VAL
		,ISNULL(SUM(ENQUIRY.BOOKED_VAL),0) AS BOOKED_VAL
		,ISNULL(SUM(ENQUIRY.INVOICED_VAL),0)AS INVOICED_VAL
		,CONVERT(VARCHAR, CONVERT(DECIMAL(6,0), (CONVERT(DECIMAL(6,2), (ISNULL(SUM(ENQUIRY.INVOICED_VAL), 0)))/CASE WHEN ((SUM(ENQUIRY.OPEN_VAL)) + (SUM(ENQUIRY.CLOSED_VAL))+(SUM(ENQUIRY.BOOKED_VAL)) + (SUM(ENQUIRY.INVOICED_VAL))) = 0 THEN 1 ELSE ((SUM(ENQUIRY.
OPEN_VAL)) + (SUM(ENQUIRY.CLOSED_VAL))+(SUM(ENQUIRY.BOOKED_VAL)) + (SUM(ENQUIRY.INVOICED_VAL))) END) * 100)) + '%' AS Con_Perc
		,1 AS RETURN_TYPE
	FROM
		(
			SELECT 
					 DEA.DEALER_ID
					,EMP.Empno AS EMPLOYEE_NO
					,EMP.Zone,EMP.Sales_Office
					,EMP.TERRITORY_KEY
					,DEA.DEALERSHIP_NAME
					,DEA.CITY
					,CASE WHEN ENQ.ENQUIRY_MODE = 'Walk-in' THEN 'WALK-IN' ELSE 'OTHERS' END AS ENQUIRY_MODE
					,CASE WHEN ENQ.STATUS = 1 THEN COUNT(*) ELSE 0 END AS OPEN_VAL
					,CASE WHEN ENQ.STATUS = 2 AND (BOOK.STATUS IS NULL OR BOOK.STATUS = 2 OR BOOK.STATUS = 3) THEN COUNT(*) ELSE 0 END AS CLOSED_VAL
					,CASE WHEN ENQ.STATUS = 2 AND (BOOK.STATUS = 1 OR BOOK.STATUS = 4) AND BOOK.STATUS IS NOT NULL THEN COUNT(*) ELSE 0 END AS BOOKED_VAL
					,CASE WHEN ENQ.STATUS = 2 AND BOOK.STATUS = 5 THEN COUNT(*) ELSE 0 END AS INVOICED_VAL
			FROM 
				JCP_DEALER_MASTER EMP WITH (NOLOCK)
				INNER JOIN DP_DEALER DEA WITH (NOLOCK)
				ON EMP.Dealer_Code = DEA.DEALER_ID
				INNER JOIN DP_ENQUIRY ENQ WITH (NOLOCK)
				ON ENQ.DEALER_ID = DEA.DEALER_ID
				LEFT OUTER JOIN DP_BOOKING BOOK WITH (NOLOCK)
				ON ENQ.DEALER_ID = BOOK.DEALER_ID
				AND ENQ.BRANCH_ID = BOOK.BRANCH_ID
				AND ENQ.ENQUIRY_ID = BOOK.ENQUIRY_ID
			WHERE 
				EMP.Empno =  @EmployeeNo 
				AND DEA.ACTIVE = 1 
				AND DEA.IS_APS IS NULL 
				AND DEA.COUNTRY_CODE = 'IN' 
				AND DEA.FOR_SYNC = 1 
				AND ENQ.ENQUIRY_DATE = Convert(date, getdate()-1)
		GROUP BY
				 DEA.DEALER_ID
				,EMP.Empno
				,EMP.Zone
				,EMP.Sales_Office
				,ENQ.STATUS
				,BOOK.STATUS
				,EMP.TERRITORY_KEY
				,DEA.DEALERSHIP_NAME
				,DEA.CITY
				--,ENQ.ENQUIRY_MODE
				,ENQUIRY_MODE
		)
		AS ENQUIRY 
		GROUP BY 
				 ENQUIRY.DEALER_ID
				,ENQUIRY.EMPLOYEE_NO
				,ENQUIRY.Zone
				,ENQUIRY.Sales_office
				,ENQUIRY.Territory_Key
				,ENQUIRY.DEALERSHIP_NAME
				,ENQUIRY.CITY
				,ENQUIRY.ENQUIRY_MODE

END
ELSE
BEGIN
SELECT 0 AS RETURN_TYPE
END
END



